# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# Include package:flutter_lints/recommended.yaml, which defines a set of recommended lints
include: package:flutter_lints/flutter.yaml

# Analyzer options
analyzer:
  # Enable the following options to enable strong mode.
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  # Enable the following options to enable new language features.
  enable-experiment:
    - patterns
    - sealed-class
    - records
    #- macros
    #- class-modifiers
    #- const-functions
    #- extension-types
    #- inference-update-2
    #- inline-class
    #- value-class
    #- variance

  # Set the following options to true to enable additional analysis.
  errors:
    # Info
    TODO: info
    directives_ordering: info
    always_declare_return_types: info

    # Warning
    unsafe_html: warning
    no_logic_in_create_state: warning
    empty_catches: warning

    # Error
    prefer_relative_imports: error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    close_sinks: error
    valid_regexps: error
    always_require_non_null_named_parameters: error

    # Disable rules
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore

# Lint rules
linter:
  rules:
    # Public packages
    public_member_api_docs: false
    lines_longer_than_80_chars: false

    # Enabling rules

    # Disable rules
