name: octopus_example
description: Library for navigation within the application
version: 0.0.1
homepage: https://github.com/PlugFox/router

publish_to: 'none'

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'
  flutter: ">=3.8.0-4.0.pre.25"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any
  octopus:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false