name: octopus
description: Library for navigation within the application
version: 0.0.1
homepage: https://github.com/PlugFox/router

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'
  flutter: '>=3.8.0-4.0.pre'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  collection: any

dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Integration tests for Flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true