name: octopus
description: Library for navigation within the application
version: 0.0.1
homepage: https://github.com/PlugFox/router

environment:
  sdk: '>=3.0.0-63.0.dev <4.0.0'
  flutter: ">=3.7.0-1.3.pre"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true